export const projects = [
  {
    id: 1,
    title: 'Free Education Classes',
    category: 'Education',
    imageId: 'project-education',
    description: 'We provide free, high-quality education to children from SC/ST communities who are often denied fair treatment in mainstream schools. Our classes offer a safe and inclusive space to learn and grow with dignity.',
    impact: 'Supporting 100+ children daily.'
  },
  {
    id: 2,
    title: 'Food and Nutrition Program',
    category: 'Health',
    imageId: 'project-health',
    description: 'To ensure our students can focus on learning, we provide nutritious meals. Good health is fundamental to a good education, and this program helps our children stay healthy and active.',
    impact: 'Serving 100+ healthy meals every day.'
  },
  {
    id: 3,
    title: 'Women & Youth Empowerment',
    category: 'Empowerment',
    imageId: 'project-women',
    description: 'We empower mothers and young adults in the community through vocational training and financial literacy, helping create a supportive environment for our children and fostering community-wide upliftment.',
    impact: 'Trained 50+ women and youth.'
  },
  {
    id: 4,
    title: 'Anti-Discrimination Campaigns',
    category: 'Advocacy',
    imageId: 'gallery-5',
    description: 'We actively run awareness campaigns to challenge and dismantle caste-based discrimination in society. Through dialogue and community engagement, we work towards a future of equality and respect for all.',
    impact: 'Reached 5,000+ community members.'
  },
];

export const blogPosts = [
  {
    id: 1,
    title: 'Bringing Education to Rural Children: Our Village Learning Program',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
    summary: 'Our Village Learning Program is transforming access to education in remote regions of Rajasthan. Through dedicated volunteer teachers, mobile learning materials, and structured activity-based sessions, we bring classroom-quality education to children who have never experienced formal schooling. The initiative focuses on reading fluency, foundational numeracy, creative learning, and personal development.',
    content: 'Education reaches the unreached through our dedicated village learning centers.',
    date: 'November 15, 2024',
    fullSummary: [
      'In the dusty lanes of remote Rajasthani villages, where the nearest government school can be 10 kilometers away, education remained a distant dream for thousands of children. OJASH WELFARE Society launched the Village Learning Program to change this reality. Today, we operate 12 learning centers across Bandikui tehsil, reaching over 450 children who previously had zero access to formal education. Our volunteer teachers travel daily to these remote hamlets, setting up classrooms under peepal trees, in community halls, and even in converted cowsheds—wherever children can gather to learn.',
      'What makes our program unique is the holistic approach we take. We don\'t just teach the standard curriculum; we focus on building confidence, curiosity, and critical thinking. Many of our students come from families where no one has ever learned to read. For them, writing their own name for the first time is a moment of profound transformation. We have seen shy children who wouldn\'t make eye contact slowly blossom into confident students who raise their hands to answer questions. The joy on a child\'s face when they read their first sentence is indescribable—it is the moment education becomes liberation.',
      'Our teachers are specially trained to work with first-generation learners using activity-based methods, songs, games, and storytelling. We understand that children who work in fields or help with household chores cannot attend rigid school timings. Our flexible schedules accommodate their lives while ensuring consistent learning. We also provide free textbooks, notebooks, pencils, and school bags—removing every possible barrier to education. For many families, even a ₹20 notebook is an unaffordable luxury.',
      'The impact extends beyond academics. Parents who initially resisted sending children to learn now proudly share their children\'s achievements. Mothers who can\'t read ask their children to read shop boards and medicine labels. Fathers who signed with thumbprints their whole lives now watch their sons write in clean handwriting. Education is creating ripples of change that touch entire families. One mother told us, "My daughter teaches me numbers at night. For the first time, I can count my own money." These moments remind us why every child deserves the gift of education.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 2,
    title: 'A Library of Hope: Opening Doors to Knowledge',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=900&q=80',
    summary: 'Our community library initiative has become a sanctuary of learning for village children. With access to books, quiet study corners, and guided reading support, students now have the opportunity to explore stories and subjects beyond their limited surroundings. The library nurtures imagination, strengthens academic skills, and empowers children to dream bigger.',
    content: 'Books open doors that poverty tries to close.',
    date: 'October 20, 2024',
    fullSummary: [
      'In January 2024, OJASH WELFARE Society opened the doors of "Gyan Ghar"—a community library in the heart of Bandikui that has since transformed into a beacon of hope for hundreds of children. The library houses over 3,000 books in Hindi and English, covering everything from textbooks to storybooks, science encyclopedias to biographies of great leaders. For children who have never owned a book, this library is nothing short of magical. Every afternoon, the reading room fills with eager faces, small fingers tracing words on pages, and whispered excitement as children discover new stories.',
      'The library was built from the ground up with community participation. Local craftsmen constructed the shelves, women\'s groups donated curtains, and children themselves helped paint the colorful walls. This sense of ownership has made Gyan Ghar truly belong to the community. We operate on a simple principle: any child can borrow any book, no questions asked, no fees charged. We believe that access to knowledge should never depend on the thickness of one\'s wallet. In a region where most families cannot afford a single storybook, our library has democratized reading.',
      'Beyond lending books, Gyan Ghar hosts weekly storytelling sessions where village elders share folk tales and volunteers read aloud from picture books. We organize monthly "Reading Champions" competitions that have sparked healthy rivalry among students from different villages. The library also serves as a quiet study space for students preparing for board exams—many of whom live in single-room homes where studying is impossible. One student, Mohit, told us he scored 85% in his 10th boards by studying every evening at Gyan Ghar. Without the library, he would have failed.',
      'The ripple effects of Gyan Ghar extend far beyond reading. Children who were glued to mobile phones now eagerly await library hours. Parents report improved language skills and vocabulary in their children. Teachers notice better comprehension and creativity in classwork. We have even started an adult literacy corner where mothers learn to read alongside their children every Sunday morning. Our dream is to establish five more such libraries across rural Dausa district. Every book we add, every child who reads, brings us closer to a more educated, empowered India.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 3,
    title: 'Women Empowerment = Educated Children',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=900&q=80',
    summary: 'When mothers learn, families rise. Our women empowerment programs offer skill-building workshops, awareness sessions, and financial literacy training to rural women, enabling them to contribute confidently to their households and communities. Educated mothers are far more likely to prioritize their children\'s schooling, nutrition, and emotional well-being.',
    content: 'Empowered mothers raise educated children who change the world.',
    date: 'September 25, 2024',
    fullSummary: [
      'At OJASH WELFARE Society, we discovered early on that the most powerful catalyst for children\'s education is an empowered mother. Our "Shakti Mata" program works with mothers in rural communities, providing them literacy training, financial education, and vocational skills. The results have been extraordinary: children of program participants show 40% higher school attendance and significantly better academic performance. When a mother can read, she reads to her children. When she understands the value of education, she fights for her children\'s schooling even against societal pressure.',
      'The program began with 25 women in one village and has now expanded to reach 200 mothers across 15 villages. We teach basic literacy, numeracy, and digital skills like using smartphones for educational apps. But more importantly, we build confidence. Many women who joined our program had never spoken in public, never made a decision without their husband\'s permission, never believed they could learn anything new. Today, these same women lead parent-teacher meetings, help their children with homework, and make informed decisions about their family\'s future.',
      'Kamla Bai\'s story exemplifies our program\'s impact. A mother of four who never attended school, she joined Shakti Mata two years ago. Today, she can read Hindi newspapers, operates a mobile phone, and runs a small tailoring business from home. More importantly, all four of her children now attend school—something she once thought impossible. "I was blind," she says, "not because I couldn\'t see, but because I couldn\'t read. Now I see everything clearly, and I want my daughters to see even more." Her eldest daughter now dreams of becoming a teacher.',
      'We have also established women\'s self-help groups that save collectively and support each other during emergencies. These groups have become powerful advocates for children\'s education in their communities. When families consider pulling girls out of school for marriage, these women intervene. When children face discrimination, these mothers speak up. The program has created a network of education champions who ensure no child in their community is denied schooling. Empowering women isn\'t just a goal—it\'s a strategy that multiplies impact across generations.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 4,
    title: 'Village Scholarship Support Programme',
    image: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
    summary: 'Our scholarship initiative supports academically strong students from economically challenged families, ensuring that financial constraints never stop a child from pursuing education. The program covers textbooks, uniforms, tuition support, and necessary learning materials. Many of these children are the first in their family to attend school beyond primary levels.',
    content: 'A scholarship today creates a leader tomorrow.',
    date: 'August 10, 2024',
    fullSummary: [
      'For Sunita, the daughter of a brick kiln worker, the dream of studying beyond 8th grade seemed impossible. Her family\'s ₹6,000 monthly income barely covered food and rent, leaving nothing for school fees, books, or uniforms. When OJASH WELFARE Society\'s scholarship reached her, it changed everything. Today, Sunita is in 11th grade, topping her class in science, and dreams of becoming a nurse to serve her community. Her story is one of 85 such transformations through our "Vidya Jyoti" scholarship program, which supports meritorious students from the poorest families.',
      'Our scholarship covers not just tuition fees but all hidden costs that force poor children out of school—uniforms, books, stationery, exam fees, and transport. We provide ₹12,000 to ₹25,000 per student annually depending on their grade level and needs. But money is only part of the support. Each scholar is paired with a mentor who provides guidance, monitors progress, and helps navigate challenges. Regular counseling sessions address the psychological barriers that first-generation learners face in competitive academic environments.',
      'The selection process for our scholarships is rigorous yet compassionate. We look for students who show dedication despite difficult circumstances—children who walk 5 kilometers to school, who study under streetlights because their homes have no electricity, who help with family work yet maintain good grades. Economic need is verified through home visits, and academic potential is assessed through interviews and school records. We prioritize girls and children from marginalized communities who face additional barriers to education.',
      'The impact of our scholarship program extends far beyond individual students. When one child from a village goes to college, it inspires dozens of others. Parents who once saw education as a waste of time now encourage their children to study harder. Our scholars return during vacations to teach younger children, creating a beautiful cycle of giving back. Last year, three of our early scholars cleared competitive exams—two are now studying nursing, and one is training to become a teacher. Every scholarship we give plants a seed that will bear fruit for generations.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 5,
    title: 'Evening Learning Classes for 100+ Children',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
    summary: 'Every evening, our community classrooms come alive with over 100 children eager to learn in a supportive environment. Volunteers conduct lessons on core subjects, provide homework help, and teach essential life skills. These sessions offer structure, guidance, and academic reinforcement for children who lack a proper learning environment at home.',
    content: 'Volunteers are the heart of our educational mission.',
    date: 'July 05, 2024',
    fullSummary: [
      'When government schools close at 2 PM, education stops for most village children. Their parents work in fields or construction sites, unable to help with homework or provide additional learning support. OJASH WELFARE Society\'s Community Classroom program fills this critical gap. Every evening from 4 PM to 7 PM, our centers transform into vibrant learning spaces where over 120 children receive supplementary education, homework help, and enrichment activities. The classrooms buzz with energy as children who struggled in school discover they can actually learn and excel.',
      'Our volunteer force is the backbone of this program. We have 35 active volunteers—college students, retired teachers, young professionals, and even some of our former students who have grown up and want to give back. Each volunteer commits to at least 6 hours per week and receives training in child psychology, teaching methods, and activity-based learning. They don\'t just teach subjects; they become mentors, role models, and friends to children who often lack positive adult figures in their lives. The bond between volunteers and students is beautiful to witness.',
      'The curriculum goes beyond textbooks. We teach spoken English through songs and conversations—a skill that opens doors in today\'s India. We conduct science experiments using household items, making abstract concepts tangible. Art and craft sessions nurture creativity. Sports and games build teamwork and confidence. Special sessions on values, hygiene, and life skills prepare children for challenges beyond academics. Every Saturday, we hold "Talent Hour" where children showcase their abilities—singing, dancing, storytelling, or even solving math problems on the board.',
      'The transformation in children is remarkable. Rahul, who was labeled "slow" in school, discovered he has exceptional drawing skills and now dreams of becoming an artist. Meena, who was too shy to speak, now confidently recites poetry in front of the entire class. Academic results have improved dramatically—children in our program show 30% better scores than before joining. But more than grades, we celebrate changed attitudes. Children who dreaded school now love learning. Parents who saw education as a burden now support it actively. This is the power of community education.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 6,
    title: 'School Kit Distribution Drive – 20 Villages, 500 Children',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
    summary: 'Our annual school-kit distribution ensures that every child has access to basic learning tools such as notebooks, pencils, school bags, geometry kits, and stationery. Many families cannot afford these essentials, causing children to miss school or feel discouraged. This year, we supported 500 children across 20 villages, enabling them to start their academic year with motivation and hope.',
    content: 'A pencil in a child\'s hand is a powerful tool for change.',
    date: 'June 01, 2024',
    fullSummary: [
      'Every June, as schools reopen after summer vacation, poor families face an impossible dilemma: spend ₹500-1000 on school supplies or use that money for food. For daily wage workers earning ₹300 per day, buying notebooks, pencils, and school bags is a luxury they cannot afford. This is why OJASH WELFARE Society\'s "Shiksha Kit" distribution has become one of our most impactful programs. This year, we distributed comprehensive school kits to 500 children across 20 villages, ensuring that no child starts the academic year without essential supplies.',
      'Each Shiksha Kit is carefully assembled based on grade level and includes: 10 notebooks, pencil box with pencils, erasers and sharpeners, geometry box for older students, school bag, water bottle, and a set of colorful crayons. For girls in higher classes, we also include sanitary napkins—addressing a significant cause of school dropouts. The total value of each kit is approximately ₹600, but for families struggling to survive, this is a month\'s worth of savings. By removing this financial barrier, we keep thousands of children in school.',
      'The distribution day is always emotional. Children line up hours before the event, excitement visible on their faces. When they receive their kits, many hug their new bags tightly, as if they\'ve received the most precious gift. Parents watch with tearful eyes, grateful that their children can attend school with dignity. One mother told us, "Last year, my son took his sister\'s old torn bag. He was ashamed. This year, he walks to school proudly with his new blue bag." These moments remind us why we do this work.',
      'Beyond distribution, we track each child\'s attendance and academic progress throughout the year. Our field workers visit families monthly to ensure children are actually using the supplies and attending school regularly. We also conduct awareness sessions with parents about the importance of education and how to support their children\'s learning at home. The Shiksha Kit is not just a bag full of supplies—it\'s a statement that we believe in every child\'s potential. And year after year, these children prove us right.',
    ],
    summaryImages: [
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80',
    ],
  },
];

export const partners = [
  { id: 1, name: 'Hope Foundation', imageId: 'partner-1' },
  { id: 2, name: 'Global Corp', imageId: 'partner-2' },
  { id: 3, name: 'Unite for Change', imageId: 'partner-3' },
  { id: 4, name: 'People\'s Trust', imageId: 'partner-4' },
];

export const events = [
  {
    id: 1,
    title: "Community Education Drive",
    date: "November 2024",
    location: "Bandikui, Dausa, Rajasthan",
    beneficiaries: "200+ Children",
    category: "Education",
    shortDescription: "Our Community Education Drive brought teachers, volunteers, and parents together to support underprivileged children with hands-on learning, study materials, and motivational sessions.",
    fullDescription: [
      "Our Community Education Drive brought teachers, volunteers, and parents together to support underprivileged children with hands-on learning, study materials, and motivational sessions.",
      "The drive focused on building foundational skills, improving classroom confidence, and offering individual learning support. Many first-generation learners benefited, gaining not only educational guidance but also emotional encouragement.",
      "Special focus was placed on interactive teaching methods, making learning fun and engaging for children who had never experienced formal education before.",
      "The overwhelming participation from the community reinforces our commitment to making quality education accessible to every child, regardless of their economic background.",
    ],
    images: [
      "/images/IMG-20250927-WA0001.jpg",
      "/images/IMG-20250927-WA0002.jpg",
      "/images/IMG-20250927-WA0003.jpg",
      "/images/IMG-20250927-WA0004.jpg",
    ],
    featured: true,
  },
  {
    id: 2,
    title: "Health Awareness Camp",
    date: "October 2024",
    location: "Remote Villages, Dausa District",
    beneficiaries: "300+ Families",
    category: "Healthcare",
    shortDescription: "This free health camp educated rural communities about hygiene, nutrition, preventive healthcare, and early diagnosis through checkups and awareness sessions.",
    fullDescription: [
      "This free health camp educated rural communities about hygiene, nutrition, preventive healthcare, and early diagnosis.",
      "Doctors and volunteers conducted basic checkups, distributed hygiene kits, and explained daily habits for better health. The camp helped families understand how small lifestyle changes can prevent long-term illnesses.",
      "Free medicines were distributed to those in need, and referrals were provided for cases requiring specialized treatment. Health education sessions covered topics like nutrition, sanitation, and disease prevention.",
      "The camp served as a lifeline for villagers who rarely have access to quality healthcare, bringing medical services right to their doorstep.",
    ],
    images: [
      "/images/IMG-20250927-WA0005.jpg",
      "/images/IMG-20250927-WA0006.jpg",
      "/images/IMG-20250927-WA0007.jpg",
      "/images/IMG-20250927-WA0008.jpg",
    ],
    featured: true,
  },
  {
    id: 3,
    title: "Women Empowerment Workshop",
    date: "September 2024",
    location: "Gram Panchayat Bhavan, Bandikui",
    beneficiaries: "150+ Women",
    category: "Women Empowerment",
    shortDescription: "Our Women Empowerment Workshop encouraged skill-building, financial literacy, self-confidence, and leadership for women in rural communities.",
    fullDescription: [
      "Our Women Empowerment Workshop encouraged skill-building, financial literacy, self-confidence, and leadership for women in rural communities.",
      "Through interactive sessions, group discussions, and training modules, many women discovered new opportunities for self-employment and independence.",
      "Hands-on sessions in tailoring, handicrafts, and basic computer skills equipped women with marketable abilities. Many participants have since started their own small businesses.",
      "Financial literacy workshops taught women about savings accounts, government schemes, and basic banking. For many, this was the first time they managed their own finances.",
    ],
    images: [
      "/images/IMG-20250927-WA0009.jpg",
      "/images/IMG-20250927-WA0010.jpg",
      "/images/IMG-20250927-WA0011.jpg",
      "/images/IMG-20250927-WA0012.jpg",
    ],
    featured: false,
  },
  {
    id: 4,
    title: "Child Nutrition Program",
    date: "August 2024",
    location: "OJASH Seva Kendra, Bandikui",
    beneficiaries: "100+ Children Daily",
    category: "Food Security",
    shortDescription: "This initiative provides nutritious meals and dietary awareness for children from economically disadvantaged backgrounds, ensuring stronger immunity and better focus.",
    fullDescription: [
      "This initiative provides nutritious meals and dietary awareness for children from economically disadvantaged backgrounds.",
      "Proper nutrition ensures stronger immunity, better focus in school, and healthy development. The program continues to support more than 100 children daily.",
      "The community kitchen runs daily, serving fresh, home-cooked meals prepared with care by dedicated volunteers. Children sit together, sharing meals and building friendships.",
      "Regular health checkups monitor each child's growth, and nutritional supplements are provided to those showing signs of malnutrition. The transformation in children's health has been remarkable.",
    ],
    images: [
      "/images/IMG-20250927-WA0013.jpg",
      "/images/IMG-20250927-WA0014.jpg",
      "/images/IMG-20250927-WA0015.jpg",
      "/images/IMG-20250927-WA0001.jpg",
    ],
    featured: true,
  },
  {
    id: 5,
    title: "School Kit Distribution Drive",
    date: "July 2024",
    location: "Multiple Villages, Bandikui Tehsil",
    beneficiaries: "500+ Children",
    category: "Education",
    shortDescription: "As part of our education support efforts, we distributed essential school kits including notebooks, pencils, bags, and drawing materials to encourage regular school attendance.",
    fullDescription: [
      "As part of our education support efforts, we distributed essential school kits including notebooks, pencils, bags, and drawing materials.",
      "The event encouraged children to attend school regularly and gave them the tools they need to participate in classroom activities confidently.",
      "Each kit was carefully assembled based on grade level, ensuring students had everything they needed for the academic year. The distribution covered 20 villages across the district.",
      "Beyond material support, we conducted motivational sessions encouraging children to dream big. Many of these first-generation learners now aspire to become teachers, doctors, and engineers.",
    ],
    images: [
      "/images/IMG-20250927-WA0002.jpg",
      "/images/IMG-20250927-WA0003.jpg",
      "/images/IMG-20250927-WA0004.jpg",
      "/images/IMG-20250927-WA0005.jpg",
    ],
    featured: true,
  },
  {
    id: 6,
    title: "Community Cleanliness Initiative",
    date: "June 2024",
    location: "Multiple Villages, Dausa District",
    beneficiaries: "10+ Villages",
    category: "Environment",
    shortDescription: "Volunteers and local families participated in a cleanliness and awareness drive aimed at encouraging healthy surroundings and community responsibility.",
    fullDescription: [
      "Volunteers and local families participated in a cleanliness and awareness drive aimed at encouraging healthy surroundings.",
      "The event promoted waste segregation, proper disposal, and community responsibility. Children actively participated, learning how a clean environment improves daily life.",
      "Awareness sessions covered topics like proper waste segregation, recycling, and maintaining clean water sources. Community members pledged to keep their surroundings clean.",
      "The initiative also included planting saplings and creating designated waste disposal areas in villages. Environmental responsibility is now a shared value in these communities.",
    ],
    images: [
      "/images/IMG-20250927-WA0006.jpg",
      "/images/IMG-20250927-WA0007.jpg",
      "/images/IMG-20250927-WA0008.jpg",
      "/images/IMG-20250927-WA0009.jpg",
    ],
    featured: false,
  },
];

export const teamMembers = [
  { id: 1, name: 'Aanya Sharma', designation: 'Founder & President', imageId: 'founder' },
  { id: 2, name: 'Rohan Gupta', designation: 'Program Director', imageId: 'team-member-2' },
  { id: 3, name: 'Priya Singh', designation: 'Head of Community Outreach', imageId: 'team-member-1' },
  { id: 4, name: 'Vikram Mehta', designation: 'Finance Manager', imageId: 'team-member-3' },
];

export const successStories = [
    {
      id: 1,
      name: 'Priya',
      imageId: 'gallery-1',
      quote: 'I used to feel afraid of reading in class. With support from the volunteers, I gained confidence. Now, I enjoy learning every day.',
      after: 'is now a confident student excelling in her studies.',
    },
    {
      id: 2,
      name: 'Ravi',
      imageId: 'gallery-2',
      quote: 'I always felt alone until I joined OJASH programs. Here, I found friends, support, and a chance to grow.',
      after: 'has found a supportive community and dreams of becoming a teacher.',
  },
  ];
